# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9d85623425d5f6ccc1690d6f415eaa8de648bca9d5ecf6e84226a2c0aab2fb7a54b2af450ac8e54749bdec6d8b90c6597c70aaba5f12cffd67240479b58ce8aa

test:
  secret_key_base: 4c871cfe5d0c78e64c2758a204787ede1ca63552750c7a1e0dd3a639fc01099da99b758ecc516b190a0554769917affa6a5295101e0efb9f1549f1e255b679e5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
